### ISSUE TITLE
Terminus package installation issue

### ISSUE THREAD

**Issue by divymital** [ikotarid/Terminus#2]
Hi,

I wanted to use this plugin for our use case to digitize automatically from satellite imagery, However wile installing the same from Zip it gave error ( File attached ) also the plugin could not be installed from QGIS itself.

I have installed scikit-image plugin following the instructions.

Please suggest.

Thanks !
![Terminus_Installation_issue](https://user-images.githubusercontent.com/47237460/101353874-52d9a580-38ba-11eb-899a-2a9c32c82d18.png)

**Comment by ikotarid** [comment]
Hello,
could you please upload a PrintScreen with the error when installing within QGIS? Also, the name of the zip should be "terminus_processing-1.0.zip".

**Comment by divymital** [comment]
Hi,

Thanks for the response !

Today when I tried with renaming the downloaded zip file from github as suggested, Same error showed  up.

Upon installing from QGIS plugin directory screen was stuck however upon clicking on "Plugin installed successful" message displayed. while running the plugin there was errors in all the algorithms. PFA the error message in the attached file. 

Please suggest how can we make effective use of the plugin for our use.


Regards,
Divya
[Terminus Execution Error.txt](https://github.com/ikotarid/Terminus/files/5657363/Terminus.Execution.Error.txt)

**Comment by ikotarid** [comment]
Hello,
1. Could you please send me the image you are trying to segment? (my email: ikotarid@gmail.com)
2. Download the latest zip file directly from here: https://plugins.qgis.org/plugins/terminus_processing/

**Comment by divymital** [comment]
I have sent you the image link on the email. Thank !

**Comment by divymital** [comment]
I tried with the latest zip file and installed the plugin again. With the imagery I get the same error.

**Comment by ikotarid** [comment]
Ok, I can see that it has to do with the format of the image file, I will check it and come back as soon as possible.

**Comment by ikotarid** [comment]
Try saving the imagery as shown in the image below and use this as the input of the algorithm.

![save_as](https://user-images.githubusercontent.com/38152192/101465991-49e3e500-3949-11eb-8e74-3b1e256d1bef.jpg)

**Comment by divymital** [comment]
Yes , This fixed the issue. 

can you please suggest what algorithm or configuration steps I shall follow to extract the building footprints from such images. Thanks !

**Comment by divymital** [comment]
Upon changing the file type, Process was triggered however it resulted in below error at a later stage for watershed algo.

Segmenting imagery...
Converting raster to vector...
Error: Algorithm gdal:polygonize not found

Execution failed after 492.60 seconds
